[![alt-text](img/LP-School-Of-AI-black.png)](https://www.facebook.com/groups/1204328906374103/)

# Introducción a Statistical Machine Learning
## Semana I: Python para Machine Learning y Ciencia de datos 
por: [Marco Antonio Vino](https://www.linkedin.com/in/mavino)
### 1.1 Primeros pasos con Numpy


[![alt-text](img/numpy.png)](http://www.numpy.org/)

* Libreria especializada en el computo n-dimensional
* Numpy trabja elementopor elemento


La forma de importar librerias externas y asignar alias:

In [1]:
import numpy as np

comparando la eficiencia de los arrays de NumPy

In [19]:
a = np.random.randint(0,100,10**5) #generando aleatorios

In [20]:
a

array([10, 88, 30, ..., 22, 93, 70])

In [4]:
type(a)

numpy.ndarray

In [5]:
b = list(a)
b

[94,
 64,
 22,
 55,
 84,
 8,
 57,
 54,
 53,
 26,
 79,
 81,
 85,
 4,
 79,
 16,
 54,
 27,
 42,
 59,
 17,
 54,
 23,
 36,
 79,
 97,
 72,
 17,
 88,
 50,
 17,
 55,
 88,
 2,
 45,
 94,
 3,
 81,
 98,
 7,
 32,
 10,
 43,
 12,
 39,
 89,
 12,
 15,
 65,
 45,
 23,
 84,
 6,
 20,
 38,
 17,
 32,
 3,
 64,
 71,
 8,
 3,
 49,
 12,
 91,
 24,
 7,
 9,
 57,
 88,
 83,
 98,
 64,
 51,
 85,
 36,
 54,
 73,
 39,
 72,
 30,
 51,
 69,
 59,
 78,
 28,
 4,
 81,
 78,
 56,
 34,
 89,
 23,
 51,
 26,
 40,
 20,
 95,
 37,
 80,
 78,
 40,
 63,
 88,
 1,
 65,
 56,
 4,
 92,
 72,
 90,
 68,
 51,
 68,
 88,
 26,
 8,
 90,
 74,
 1,
 15,
 65,
 5,
 39,
 89,
 42,
 75,
 55,
 36,
 4,
 78,
 75,
 82,
 8,
 14,
 94,
 61,
 95,
 60,
 80,
 66,
 27,
 13,
 25,
 45,
 62,
 54,
 62,
 58,
 38,
 5,
 45,
 35,
 45,
 35,
 85,
 95,
 85,
 90,
 30,
 90,
 65,
 99,
 69,
 75,
 30,
 10,
 63,
 32,
 96,
 24,
 58,
 56,
 86,
 51,
 51,
 28,
 57,
 62,
 82,
 76,
 41,
 19,
 49,
 38,
 52,
 32,
 91,
 36,
 14,
 10,
 74,
 61,
 62,
 39,
 60,
 99,
 42,
 79,
 14,
 32,
 85,
 19,
 68,


In [6]:
type(b)

list

Comparemos el rendimiento de ambos

In [9]:
%%timeit
sum(b)

15.4 ms ± 1.12 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [10]:
%%timeit
a.sum()

144 µs ± 5.04 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


En cada ejecucion los número aleatorios son distintos ... ¿cómo hago para que cada vez que corra el código sean los mismos?

In [40]:
#np.random.seed(123)
np.random.binomial(5, 0.3, 10)

array([1, 1, 1, 2, 1, 2, 2, 1, 0, 4])

In [60]:
np.random.seed(1234)
np.random.binomial(5, 0.3, 10)

array([1, 2, 1, 2, 2, 1, 1, 2, 3, 3])

In [62]:
np.random.choice([0,1],10)

array([1, 0, 0, 1, 0, 1, 0, 0, 0, 1])

Repliquemos el ejercio de las momendas

In [64]:
def lanzarMonedas(nPar, l=10, mostrar=False):
    """
    np, es número de participantes,
    l, número de lanzamientos
    Retorna la probabilidad de que salga cara.
    """
    personas = np.zeros(l)
    for i in range(nPar):
        persona_i = np.random.choice([0,1],l)
        if mostrar: print(persona_i)
        personas += persona_i
    return personas.sum()/(nPar*l) 

In [70]:
#%%timeit
lanzarMonedas(100000)

0.500184

Puede haber una mejor implementacion, de manera matricial. 

In [72]:
def lanzarMonedaM(nPar, l=10, mostrar=False):
    """
    np: es número de participantes,
    l: número de lanzamientos
    Retorna la probabilidad de que salga cara.
    """
    personas = np.random.choice([0,1],(nPar,l))
    return personas.sum()/(nPar*l) 

In [75]:
%%timeit
lanzarMonedaM(100000)

36.1 ms ± 4.86 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [76]:
%%timeit
lanzarMonedas(100000)

9.86 s ± 3.6 s per loop (mean ± std. dev. of 7 runs, 1 loop each)


# Las operaciones matriciales nos permiten ganar eficiencia en los tiempos de ejecución

## Operaciones matriciales con NumPy

$$\begin{bmatrix}
    x_{11} & x_{12} & x_{13} & \dots  & x_{1m} \\
    x_{21} & x_{22} & x_{23} & \dots  & x_{2m} \\
    \vdots & \vdots & \vdots & \ddots & \vdots \\
    x_{n1} & x_{n2} & x_{n3} & \dots  & x_{nm}
\end{bmatrix} $$

In [77]:
A = np.matrix([[1,2, 3],[5, 8, 6]])
A

matrix([[1, 2, 3],
        [5, 8, 6]])

In [78]:
A.shape  #Dimensiones 

(2, 3)

In [83]:
A[:,0] #extraer elementos

matrix([[1],
        [5]])

In [96]:
B = np.ones((2,3))
B

array([[1., 1., 1.],
       [1., 1., 1.]])

### Suma de matrices
Ambas matrices deben tener exactamente la misma dimensión
$$\begin{bmatrix}
    a_{1,1} & a_{1,2} & a_{1,3}  \\
    a_{2,1} & a_{2,2} & a_{2,3}  \\
\end{bmatrix}  
 + 
\begin{bmatrix}
    b_{1,1} & b_{1,2} & b_{1,3}  \\
    b_{2,1} & b_{2,2} & b_{2,3}  \\
\end{bmatrix}  
= 
\begin{bmatrix}
    c_{1,1} & c_{1,2} & c_{1,3}  \\
    c_{2,1} & c_{2,2} & c_{2,3}  \\
\end{bmatrix} 
 $$

In [97]:
B.shape

(2, 3)

In [98]:
C = A - B
C

matrix([[0., 1., 2.],
        [4., 7., 5.]])

### Multiplicación por un escalar
k debe ser un escalar
$$
k
\begin{bmatrix}
    1 & 2 & 3  \\
    5 & 8 & 9  \\
\end{bmatrix}
=
\begin{bmatrix}
    1k & 2k & 3k  \\
    5k & 8k & 9k  \\
\end{bmatrix}$$

In [93]:
A

matrix([[1, 2, 3],
        [5, 8, 6]])

In [95]:
k=3
k*A

matrix([[ 3,  6,  9],
        [15, 24, 18]])

### Multiplicaciones de matrices 
El número de columnas de la primera matriz debe ser el mismo que el número de filas de la segunda matriz

$$\begin{bmatrix}
    a_{1,1} & a_{1,2}  \\
    a_{2,1} & a_{2,2}  \\
\end{bmatrix}  
\begin{bmatrix}
    b_{1,1} & b_{1,2}   \\
    b_{2,1} & b_{2,2}  \\
\end{bmatrix}  
= 
\begin{bmatrix}
    c_{1,1} & c_{1,2}  \\
    c_{2,1} & c_{2,2}  \\
\end{bmatrix} 
 $$
 donde:
 $$ c_{1,1} = a_{1,1}b_{1,1} + a_{1,2}b_{2,1} $$
 $$ \vdots $$

In [99]:
print(A.shape)
print(B.shape)

(2, 3)
(2, 3)


In [100]:
X = np.matrix(np.random.randint(0, 10 , (5,5)))
X

matrix([[5, 2, 5, 7, 7],
        [0, 6, 3, 8, 3],
        [1, 7, 9, 6, 9],
        [5, 2, 2, 2, 7],
        [2, 2, 6, 5, 8]])

In [101]:
Y = np.matrix(np.random.randint(0, 10 , (5,5)))
Y

matrix([[3, 7, 7, 3, 3],
        [2, 9, 8, 4, 5],
        [9, 8, 2, 8, 0],
        [2, 7, 2, 4, 7],
        [4, 5, 4, 6, 2]])

In [103]:
X*Y # ambos elementos sean matrices

matrix([[106, 177, 103, 133,  88],
        [ 67, 149,  82,  98,  92],
        [146, 229, 129, 181,  98],
        [ 69, 118,  87,  89,  53],
        [106, 155,  84, 130,  67]])

In [104]:
type(X)

numpy.matrixlib.defmatrix.matrix

##### Transponiendo matrices

In [106]:
X

matrix([[5, 2, 5, 7, 7],
        [0, 6, 3, 8, 3],
        [1, 7, 9, 6, 9],
        [5, 2, 2, 2, 7],
        [2, 2, 6, 5, 8]])

In [105]:
X.T  #.T , .transpose()

matrix([[5, 0, 1, 5, 2],
        [2, 6, 7, 2, 2],
        [5, 3, 9, 2, 6],
        [7, 8, 6, 2, 5],
        [7, 3, 9, 7, 8]])

##### Tener mucho cuidado con el tipo de dato con el que se esta operando
$$@ != * != np.dot()$$

In [109]:
J = np.random.randint(0, 10 , (5,5))
K = np.random.randint(0, 10 , (5,5))

In [110]:
J

array([[0, 5, 2, 6, 0],
       [6, 9, 7, 9, 1],
       [5, 1, 2, 7, 2],
       [6, 9, 3, 6, 4],
       [4, 1, 6, 6, 3]])

In [111]:
K

array([[6, 4, 0, 3, 9],
       [3, 6, 7, 5, 2],
       [9, 3, 8, 3, 2],
       [1, 9, 5, 4, 0],
       [6, 1, 4, 6, 7]])

In [118]:
J@K

array([[ 39,  90,  81,  55,  14],
       [141, 181, 168, 126,  93],
       [ 70,  97,  66,  66,  65],
       [120, 145, 133, 120, 106],
       [105,  97,  97,  77,  71]])

In [115]:
suma = 0
for i in range(5):
    suma += J[0,i]*K[i,0]
suma

39

In [119]:
np.dot(J,K)

array([[ 39,  90,  81,  55,  14],
       [141, 181, 168, 126,  93],
       [ 70,  97,  66,  66,  65],
       [120, 145, 133, 120, 106],
       [105,  97,  97,  77,  71]])

## Array NO ES IGUAL a matriz

##### Inversa de la matriz

In [120]:
L = np.matrix(J)
np.linalg.inv(J)

array([[-0.24330692,  0.14414221,  0.1432855 , -0.01049475, -0.12957807],
       [ 0.03191262,  0.03127008, -0.08481474,  0.07796102, -0.05782823],
       [-0.04562005,  0.08952667, -0.16063397, -0.06446777,  0.16320411],
       [ 0.1552795 , -0.05590062,  0.1242236 , -0.04347826, -0.00621118],
       [ 0.09445277, -0.26986507, -0.08995502,  0.20389805,  0.2113943 ]])

#### Manipulación de arrays en numpy

In [147]:
A1 = np.random.random_sample(16)

In [148]:
A1

array([0.10339502, 0.17139543, 0.61712533, 0.39335088, 0.69017821,
       0.43819065, 0.75292694, 0.43262232, 0.82969138, 0.08794322,
       0.70816281, 0.32325738, 0.64955715, 0.54874835, 0.78068713,
       0.36844945])

In [149]:
A1.reshape((4,4),order="F")

array([[0.10339502, 0.69017821, 0.82969138, 0.64955715],
       [0.17139543, 0.43819065, 0.08794322, 0.54874835],
       [0.61712533, 0.75292694, 0.70816281, 0.78068713],
       [0.39335088, 0.43262232, 0.32325738, 0.36844945]])

In [150]:
A2 = A1.reshape((4,4))
A2 # Copiar sin copy 

array([[0.10339502, 0.17139543, 0.61712533, 0.39335088],
       [0.69017821, 0.43819065, 0.75292694, 0.43262232],
       [0.82969138, 0.08794322, 0.70816281, 0.32325738],
       [0.64955715, 0.54874835, 0.78068713, 0.36844945]])

In [151]:
A2

array([[0.10339502, 0.17139543, 0.61712533, 0.39335088],
       [0.69017821, 0.43819065, 0.75292694, 0.43262232],
       [0.82969138, 0.08794322, 0.70816281, 0.32325738],
       [0.64955715, 0.54874835, 0.78068713, 0.36844945]])

In [152]:
A2[1] = np.arange(1,2)
A2

array([[0.10339502, 0.17139543, 0.61712533, 0.39335088],
       [1.        , 1.        , 1.        , 1.        ],
       [0.82969138, 0.08794322, 0.70816281, 0.32325738],
       [0.64955715, 0.54874835, 0.78068713, 0.36844945]])

In [156]:
A2

array([[0.10339502, 0.17139543, 0.61712533, 0.39335088],
       [1.        , 1.        , 1.        , 1.        ],
       [0.82969138, 0.08794322, 0.70816281, 0.32325738],
       [0.64955715, 0.54874835, 0.78068713, 0.36844945]])

In [154]:
A3 = A2.copy()
A3[:,0] = 0

In [155]:
A3

array([[0.        , 0.17139543, 0.61712533, 0.39335088],
       [0.        , 1.        , 1.        , 1.        ],
       [0.        , 0.08794322, 0.70816281, 0.32325738],
       [0.        , 0.54874835, 0.78068713, 0.36844945]])

Ampliar las matrices

In [157]:
A3 = np.random.randint(1,11,(4,4))
A3

array([[ 9,  5,  8,  4],
       [ 3,  6,  3,  2],
       [ 6, 10,  2,  2],
       [ 6,  9,  7,  9]])

In [163]:
A4 = np.hstack((A2,A3)) #np.?stack()

In [170]:
A4 = A4.flatten()

max, min, sum, mean, std, argmax, argmin

In [175]:
A4.mean()

3.143180110511286

In [173]:
A4[21]

10.0

Condiciones lógicas y máscaras

In [180]:
A4 < A4.mean()

array([ True,  True,  True,  True, False, False, False, False,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
        True,  True, False, False,  True,  True,  True,  True,  True,
        True, False, False, False, False])

## Ejercicio 1
![alt-text](img/ajedrez.png)

Crea una _**array**_ de numpy que simule un tablero de ajedrez en la posición inicial, con las siguientes características: 
* casillas blancas con "W"
* casillas negras como "B".
* además los peones con "P", torres con "T", caballos con "C", alfiles con "A", reina con "Q" y rey con "R". (Aquellas casillas donde existan piezas no es necesario que se muestre el color) 


In [46]:
#ISML-W1-E1 No borrar esta línea!
#####################################
#tu código aquí



#####################################

### Ejercicio 2
Resuelve el siguiente sistema de ecuaciones con **operaciones matriciales** en numpy.  

$$
\left.
\begin{array}{rcl}
     4x+8y-z & = & -1
  \\ x-2y +z & = & 5
  \\ 3x+2y+2z & = & 12
\end{array}
\right\}
$$

In [47]:
#ISML-W1-E2 No borrar esta línea!
#####################################
#tu código aquí



#####################################

[![alt-text](img/cdd-lp-gray.png)](https://www.facebook.com/ccd.bolivia.bo/)